version: '3.2'
services:
    static_site:
      image: httpd:latest
      container_name: static-site
      ports:
        - "80:80"
      volumes:
          - ./static-site:/usr/local/apache2/htdocs/
    sauce_connect:
        environment:
          - SAUCE_USERNAME
          - SAUCE_ACCESS_KEY
          - SAUCE_TUNNEL_IDENTIFIER
        image: joscha/docker-sauce-connect:latest
        restart: always
        ports: 
          - "4445:4445"
        command: sc -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY --readyfile /ready/sc --tunnel-identifier $SAUCE_TUNNEL_IDENTIFIER
        volumes:
            - type: bind
              source: ready-volume
              target: /ready
    wdio:
        environment:
          - SAUCE_USERNAME
          - SAUCE_ACCESS_KEY
          - SAUCE_TUNNEL_IDENTIFIER
        tty: true
        image: node:latest
        ports:
          - "4444:4444"
        depends_on:
          - "sauce_connect"
          - "static_site"
        command: ./run_test.sh
        working_dir: /app
        volumes:
            - .:/app
            - type: bind
              source: ready-volume
              target: /ready
volumes:
     ready-volume: 
